### ISSUE TITLE
[Request] Add link to full list of supported wallet names

### ISSUE THREAD

**Issue by mobilekosmos** [MoralisWeb3/MoralisDocumentation#10]
[](https://docs.moralis.io/moralis-server/users/crypto-login#filter-mobile-linking-options)

I suppose the list of wallets is defined somewhere? It would be nice to link the full list in the docs.

**Comment by YosephKS** [comment]
Hey @mobilekosmos in v2 we currently are wallet agnostic for authentication, I suggest that you check out this https://docs.moralis.io/authentication-api

as this docs is deprecated and no longer will be updated
