### ISSUE TITLE
Adding Issue and PR Templates

### ISSUE THREAD

**Issue by damla** [MoralisWeb3/MoralisDocumentation#111]
## Problem

Clarifying route for PR and Issues might be quite helpful for developers ☺️

## TO-DOs

- [x] Adding [pull_request_template.md](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)
- [ ] [Adding Issue templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)

**Comment by 0xPr0f** [comment]
Nice 👌
