### ISSUE TITLE
Moralis .NET SDK using old interface

### ISSUE THREAD

**Issue by Ziden** [MoralisWeb3/MoralisDocumentation#122]
Currently theres little Moralis .NET  SDK documentation for Queries, the only available is https://github.com/ethereum-boilerplate/ethereum-unity-boilerplate

However that uses a deprecated API using MoralisInterface class.

Currently following the new SDK it seems the new way of doing it is using Moralis.Query<T> 

Perhaps worth adding documentation for query in the MoralisSDK page for .net SDK and updating that repo.

**Comment by 0xPr0f** [comment]
there is documentation on the github and official moralis docs on queries with the .NET sdk

**Comment by 0xPr0f** [comment]
hey, the docs now have this, so does the github
