### ISSUE TITLE
[Documentation] MODIFYING OBJECTS ON SAVE - missing object return statement

### ISSUE THREAD

**Issue by DenisaHalmaghi** [MoralisWeb3/MoralisDocumentation#136]
### Issue 
In the section in the documentation on [MODIFYING OBJECTS ON SAVE](https://docs.moralis.io/moralis-dapp/cloud-code/triggers#modifying-objects-on-save), the return statement for the object is missing.

### Context:
In my project I tried modifying the object I wrote the beforeSave trigger for without returning it and the changes were not saved to the database, but if I returned the modified object the changes were saved.

I also [made a Pull Request to address this issue](https://github.com/MoralisWeb3/MoralisDocumentation/pull/135)

**Comment by 0xPr0f** [comment]
nice
