### ISSUE TITLE
(Authenticating Solana users with Phantom Wallet) Incomplete

### ISSUE THREAD

**Issue by boluwatifee4** [MoralisWeb3/MoralisDocumentation#176]
The documentation for authenticating Solana users with Phantom wallet is not in tabs and seems incomplete also does not have a tab for implementation with react framework.
![image](https://user-images.githubusercontent.com/87859583/180997780-d136b336-867c-46f6-b571-f9295b1b325f.png)

**Comment by boluwatifee4** [comment]
Hello, I have made an update concerning this, I have tried creating a new branch and pushing to the new branch, but I was denied access. Please how can I get my PR up?  @k0nekt @Qudusayo  someone can help pls?

**Comment by k0nekt** [comment]
You do not have permissions to directly push into this repo, you have to fork it to make a PR. I suggest reading [this](https://opensource.com/article/19/7/create-pull-request-github)

**Comment by boluwatifee4** [comment]
> You do not have permissions to directly push into this repo, you have to fork it to make a PR. I suggest reading [this](https://opensource.com/article/19/7/create-pull-request-github)

Thanks I'll do that
