### ISSUE TITLE
The Discord channel link in the docs is a 404

### ISSUE THREAD

**Issue by cleyfe** [MoralisWeb3/MoralisDocumentation#32]
The link is no longer available in the "Contribute to Docs" section of the Moralis documentation. Link to the discord is the following one:
https://morals.io/mage

**Comment by YosephKS** [comment]
Thank you @cleyfe I think this can be fixed 🙌🏼

**Comment by YosephKS** [comment]
@cleyfe Alright fixed! 🙌🏼

**Comment by thetwosents** [comment]
Is this still open?
