### ISSUE TITLE
Pricing page is down

### ISSUE THREAD

**Issue by dcts** [MoralisWeb3/MoralisDocumentation#62]
On this page:
https://docs.moralis.io/misc/faq#sleeping-servers

The link to pricing is redirecting to moralis.io/pricing

## But I get 502 bad gateway
![Bildschirmfoto vom 2022-03-01 17-18-15](https://user-images.githubusercontent.com/44790691/156206567-389318e8-c133-4836-96cb-1772579f1c68.png)

**Comment by abdulmalik97** [comment]
This has been fixed.
